name: Update AWS ECS Service

on:
  workflow_call:
    inputs:
      awsRegion:
        required: true
      awsCluster:
        required: true
      awsService:
        required: true
    secrets:
      awsId:
        required: true
      awsToken:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: Login to AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.awsId }}
        aws configure set aws_secret_access_key ${{ secrets.awsToken }}
        aws configure set default.region ${{ inputs.awsRegion }}
    
    - name: Run Deploy Command
      run: aws ecs update-service --cluster ${{ inputs.awsCluster }} --service ${{ inputs.awsService }} --force-new-deployment
