name: Deploy

on:
  workflow_run:
    workflows: [ Build ]
    branches: [ production ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: Fake Deploy
      run: exit 0
